### Numpy
1. Short for **num**erical **py**thon
2. Introduces many useful mathematical functions, such as rng, linalg, Fourier transforms, and so much more!
3. Provides a powerful new data structure: the **ndarray**
4. Faster than native python!

So, let's get started!

In [1]:
import numpy as np
print(f"Installed version of numpy: {np.__version__}")  

Installed version of numpy: 1.20.2


### Arrays

1. Acts similar(ish) to a list
2. Allows for fast operations, and occupies less memory than a list!
3. Actual name: the ndarray - N Dimensional Array

Let's start by making our first array!

In [2]:
arr = np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
# You can create one from a tuple too!
arr_tup = np.array((1,2,3,4,5))
print(type(arr_tup))

<class 'numpy.ndarray'>


### Putting the n-d in ndarray
Arrays allow for the easy creation of n-dimensional lists of objects. This means that they allow for easy representation of vectors, matrices, and tensors, all of which have uses in machine learning, as well as many other areas of scientific computing (particularly for physicists). 

Here are a few examples: 

In [4]:
# Create a 2D array of size 2*3 
arr_2d = np.array([[1,2,3], [4,5,6]])
print(f"2D array from list {arr_2d}")

2D array from list [[1 2 3]
 [4 5 6]]


In [5]:
# Create an array of zeroes of specified shape - (Specified in a tuple): 
arr_2d_zeros = np.zeros((4,3))
print(f"2D array of zeroes {arr_2d_zeros}")

2D array of zeroes [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Create an array of ones of specified shape - (Specified in a tuple): 
arr_2d_ones = np.ones((2,4))
print(f"2D array of ones {arr_2d_ones}")

2D array of ones [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
#Let's make a 3D array!
arr_3d = np.zeros((2,3,4))
print(f"3D array: {arr_3d}")

3D array: [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [8]:
# We even have 0D arrays!
arr_0d = np.array(3)
print(arr_0d)

3


### Slice n' Index!
1. For 1D arrays, we can index and slice similar to python lists. 
2. For 2D and higher dimensional arrays, we simply state the slices/indices we want, separated by commas.|

In [ ]:
# Get first 3 elements of 1D array
print(arr[:3])

In [ ]:
# Get first row and second and third colums from arr_2d
print(arr_2d[0, 1:3])

In [ ]:
# Change out multiple entries!
arr_3d[1,1,:] =[1,2,4,5]
print(arr_3d)

### Array properties - broadcasting
A key feature of arrays is their ability to broadcast operations - that is, to carry out an operation over every element in the array!
This is much faster than simply looping through a list and doing the same operation. 
Let us first look at an example of array broadcast, and compare it to a list!

NOTE: ARRAY BROADCASTING ONLY WORKS WITH ARRAYS OF COMPATIBLE SIZES

In [9]:
def list_adding_time(list1,list2):
    out = []
    for i in range(len(list1)):
        out.append(list1[i] + list2[i])
    return out
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
%timeit list_adding_time(list1,list2)

702 ns ± 0.478 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
def arr_broadcast_time(arr1, arr2):
    return arr1 + arr2
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
%timeit arr_broadcast_time(arr1, arr2)

354 ns ± 1.11 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### No free lunch!
There is a price that we must pay for this speed. There are 2 restrictions on numpy arrays:
1. All elements must be of the same type
2. Arrays cannot be resized

These restrictions stem from how numpy arrays get their speed: 
1. Arrays are stored in contiguous areas in memory
2. Numpy is written in C, and thus the functions of numpy benefit from being processed close to the metal

### Useful functions in Numpy: 
Numpy has a lot of functions for general utility as well! Let us examine a few of them!

In [ ]:
# Find the mean of an array:
print(np.mean(arr))

In [ ]:
# Find standard deviation of values in an array 
print(np.std(arr))

In [ ]:
# arange - return list of numbers given a step size between a start and an endpoint
print(np.arange(2, 3, step = 0.09))
# linspace : return a certain number of evenly spaced points between 2 numbers
print(np.linspace(2, 3, num = 6))

### Linear Algebra 
Numpy offers support for many linear algebra functions, which is significant for machine learning as well as in other fields, like physics, engineering, and mathematics!

By the way, the inbuilt matrix object in numpy is deprecated. We will instead show how numpy arrays can be used in matrix computations.

In [ ]:
#Create 3 Matrices and 2 vectors - 
mat_A = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat_B = np.array([[1,4,9], [2,5,8]])
mat_C = np.array([[1,0, 5], [2,4,7] , [8, 9, 3]])
vec_D = np.array([[1], [2],[3]])
vec_E = np.array([[3 , 8, 7]])

### Basic Operations
Numpy supports all basic matrix operations, including addition, inner products, matrix multiplication. It also supports many advanced operations as well! For now, we will go through some of them!

In [ ]:
# Addition
print(mat_A + mat_C)

In [ ]:
# Matrix multiplication
print(mat_B @ mat_A)

In [ ]:
# Note - * is elementwise multiplication, NOT matrix multiplication!
print(mat_A * mat_C)
print(mat_A @ mat_C)

In [ ]:
# Matrix times a vector
print(mat_B @ vec_D)

In [ ]:
# Take transpose of matrix
print(np.transpose(mat_B))

In [ ]:
# Get dot product 
print(np.dot(vec_E, vec_D))

In [ ]:
# Get norm of a vector
print(np.linalg.norm(vec_D))

In [ ]:
# Get eigenvalues and eigenvectors for a matrix
print(np.linalg.eig(mat_A))